name: 'Setup Unity Project'

inputs:
  unityVersion:
    required: true
  projectPath:
    required: true
  manifest:
    required: true
runs:
  using: 'composite'
  steps:
    # Unityプロジェクトを配置
    - name: Create directory
      if: ${{ inputs.projectPath != '' }}
      run: mkdir -p ${{ inputs.projectPath }}
      shell: bash
    - name: Create minimal project contents
      working-directory: ${{ inputs.projectPath }}
      run: |
        mkdir Assets
        mkdir Packages
        mkdir ProjectSettings
        echo "m_EditorVersion: ${{ inputs.unityVersion }}" > ProjectSettings/ProjectVersion.txt
      shell: bash
    - name: Create manifest.json
      uses: jsdaniell/create-json@v1.2.3
      working-directory: ${{ inputs.projectPath }}
      with: 
        name: "Packages/manifest.json"
        json: ${{ inputs.manifest }}
